version: '3'
services:
    redis:
        image: redis
        container_name: redis
    kafka:
        image: bitnami/kafka
        container_name: kafka
        environment:
         - ALLOW_PLAINTEXT_LISTENER=yes
    application:
        build:
           context: .
           dockerfile: ./Dockerfile
        ports:
            - "8080:8080"

